# Generated by Django 3.0.4 on 2020-03-31 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('url_short', models.URLField(blank=True, null=True)),
                ('heading_text', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(default=None)),
                ('friends', models.ManyToManyField(related_name='_expert_friends_+', to='expert.Expert')),
            ],
        ),
    ]
